name: CI ##The name of the workflow
on:
  push: ##Triggers the workflow when there is a push to the remote repo
  pull_request: ##Triggers the workflow when there is a pull request to the remote repo
  workflow_dispatch: ##Triggers the workflow manually
jobs:
  test:
    runs-on: ubuntu-latest ##The OS on which the job will run
    steps:
      - uses: actions/checkout@v4 ##Checks out the code from the repo

      - name: Setup PHP ##Sets up the PHP environment
        uses: shivammathur/setup-php@v2 ##Uses the set up php action
        with:
          php-version: "8.2"
          extension: mbstring, intl, pcntl, pdo_sqlite, sqlite3
          coverage: none ##No coverage is needed for this workflow

      - name: Cache Composer
        uses: actions/cache@v4 ##Uses the cache action
        with:
          path: |
            ~/.composer/cache/files
            vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies #Install the dependencies for
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare app key for tests
        run:
          | ##Copies the .env.example file to .env and generates a new app key so the tests can run
          cp .env.example .env
          php artisan key:generate --ansi

      - name: Run tests
        run: php artisan test --without-tty --stop-on-failure
