name: Feature CI ##The name of the workflow
on:
    push:
        branches: [ "feature/**" ]

permissions:
    contents: write ##it can modify the repo files
    pull-requests: write #It can open/edit/close PRs


jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: shivammathur/setup-php@v2
          with: { php-version: '8.2' }
        - run: composer install --no-interaction --prefer-dist --no-progress
        - run: php artisan test --testsuite=Unit #Target the test/unit dir
    open_pr_on_green:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Create/label PR to main
          env: 
            GH_TOKEN: ${{ github.token }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            set -Eeuo pipefail
            BASE=main
            HEAD="${{ github.ref_name }}"
            gh pr view "$HEAD" --repo "$GITHUB_REPOSITORY" || \
            gh pr create \
            --base "$BASE" \
            --head "$HEAD" --title "feat: $HEAD" \
            --body "Auto PR after green Feature CI." \
            --add-label "automerge" #CRITICAL POINT
    CI-full:  ##Reusable Workflow
        needs: [test, open_pr_on_green]
        uses: ./.github/workflows/ci.yml
        with: { php-version: '8.2' }
    # laravel-tests:
    #     needs: [test, open_pr_on_green]
    #     uses: ./.github/workflows/laravel.yml
    #     with: { php-version: '8.2' }
 