name: Feature CI ##The name of the workflow
on:
    push:
        branches: [ "feature/**" ]

permissions:
    contents: write ##it can modify the repo files
    pull-requests: write #It can open/edit/close PRs


jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: shivammathur/setup-php@v2
          with: { php-version: '8.2' }
        - run: composer install --no-interaction --prefer-dist --no-progress
        - run: php artisan test --testsuite=Unit #Target the test/unit dir
      