name: Auto merge on PR labeled automerge
on:
    workflow_run:
        workflows: [ "CI" ]
        types:
            - completed
    pull_request:
        types: [ labeled, opened, synchronize, reopened, ready_for_review ]
            # Check if the PR is labeled for auto-merge
            # Check if the PR is created
            # Check if the PR is updated
            # Check if the PR is re open
            # Check if the PR is marked as ready for review
    workflow_dispatch:
permissions:
  contents: read
  pull-requests: write

jobs:
    enabled_automerge:
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            github.event.pull_request.base.ref == 'main' &&
            contains(github.event.pull_request.labels.*.name, 'automerge')

        runs-on: ubuntu-latest
        steps:
            - uses: peter-evans/enable-pull-request-automerge@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                merge-method: squash