name: Open Pull request ##The name of the workflow
on:
  workflow_run:
    workflows: ["Feature CI"]
    types:
      - completed
jobs:
    opens-pr-on-green:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
          - uses: actions/checkout@v4
          - name: Ensure GH CLI
            uses: cli/cli-action@v2
          - name: Create or update PR to main 
            env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
            run: |
              BASE="main"
              HEAD="${GITHUB_REF_NAME}" # Feature branch name
              # If PR exists, do nothing; else create one
              gh pr view "$HEAD" --repo "$GITHUB_REPOSITORY" || \
              gh pr create \
                --base "$BASE" \
                --head "$HEAD" \
                --title "feat: ${HEAD}" \
                --body "Auto PR created after the feature branch finished."
              
